query {
  pandocImport {
    config {
      enabled
      defaultOutputFormat
      enableWikiNormalizer
      enableAutoTypeDetection
      fallbackReader
      allowedFileTypes
      maxFileSize
      showWarnings
      pandocBinaryPath
    }
  }
}
