mutation ($config: PandocImportConfigInput!) {
  pandocImport {
    saveConfig(config: $config) {
      responseResult {
        succeeded
        errorCode
        slug
        message
      }
    }
  }
}
