query ($query: String!) {
  pages {
    search(query:$query) {
      results {
        id
        pageId
        title
        description
        path
        locale
        contentMode
        sectionType
        sectionIndex
        sectionKey
        sectionHeading
        sectionAnchor
        snippetPreview
      }
      suggestions
      totalHits
    }
  }
}
